pex_pytest: Support licenses attribute to allow rules in third_party
Commit 0e8c2e865a added the "licenses" attribute to pex_attrs, so
it applies to all the "real" PEX rules. However, pex_pytest is a
macro, so it needs the attribute added as well. Fixes the following
error when using pex_pytest in a third_party subdirectory:

ERROR: third_party/example/BUILD:10:1: third-party rule
'//third_party/example:example_test' lacks a license declaration with
one of the following types: notice, reciprocal, permissive,
restricted, unencumbered, by_exception_only

third_party/example/example_test.py: A test for this issue.